[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.27.1"
vulkano-shaders = "0.27.1"
winit = "0.25"
vulkano-win = "0.27.1"
image_reading = { version="0.24", package = "image" }